version: "3.8"
services:
  postgres:
    image: postgres:latest
    volumes:
      - docketeerdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docketeer-db
volumes:
  docketeerdb:
