# Postgres 15 was the latest functioning version as of 10/26/22

version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: docketeer-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docketeer-db
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./docketeerdb:/var/lib/postgresql/data/
    restart: always
    mem_limit: 400m
    cpus: 0.5
volumes:
  schema: {}
  docketeerdb: {}
